name: DevOps Demo CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Application
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: devops-demo-app
          path: target/*.war
